### ISSUE TITLE
Writing Packages link in readme.md does not work

### ISSUE THREAD

**Issue by genyded** [foxbenjaminfox/meteor-coffeescript#3]
The Writing Packages link in the readme.md does not work from Gihub or Atmosphere. It points to https://github.com/foxbenjaminfox/meteor-coffeescript/blob/master/#writingpackages which does not exist. I am new to coffeescript and trying to detemine if packages can be written in CS and/or how to export globals. It would be nice to get to some info related to that.

**Comment by foxbenjaminfox** [comment]
I do apologize for the broken link. I'll fix it, and maybe clear up the readme around it a bit. The broken link comes from the preforked parent package, and it's broken also there.

The matter is quite simple: you can indeed write packages in coffescript. You add a depency on the package as normal, and you write you package in coffescript. All top-level variables declared as exported in the package.js file get automatically hoisted to the global scope.

In other words, if you've written Meteor packages in the past, it's the exact same thing. You just need coffescript as a dependency (load it _before_ you load your coffescript files, of course), and you define exported variables in package.js just like you would in javascript. It isn't that difficult, but if it somehow isn't working for you, or if some part of my explanation is insufficient, let me know and I can provide more detailed, step by step help and advice. (If you want it.)

I'm always happy to help anyone I treated in using CoffeeScript and Meteor,so feel free to ask about any additional details you feel I missed. (I plan on updaing the readme with approximately the same explanation I gave here.)

**Comment by genyded** [comment]
Cool and thanks,,, the one area that is not very clear is the use of @ (for globals?). Some of the articles have examples like:

Users = {} # This is a local variable
@Users = Users # Globalize your variable

... is it possible to just do something like:

@Users = Users {}

...instead? I assume then that in either case, the export would then just be User and not @Users? Making that clear in the updated readme with a sample would be great. From what I've seen and read, that seems to be the most confusing aspect.

**Comment by foxbenjaminfox** [comment]
Remember, @ means `this` in CoffeeScript, which in this case is the window object. This is a hack to escape the automatic `var`ing CoffeeScript does to variables.

This is unnecessary if you are exporting your variable. The package itself identifies that it needs to be in the global scope, and hoists it there for you. Yeah, I agree it could be clearer. I'll see about adding it to the readme. (I personally didn't write most of the readme, just the bits where I explain the new stuff provided. But better documentation helps everyone, so I guess it would be a good idea for me to invest some work in that as well.)
